/**
 * Another test of ensuring name uniqueness within a scope. 
 * Here we have an exception definition containing identically-named
 * fields. 
 * RESULT: passed by the idl compiler
 */
 
 exception BadEx_2 {
   string reason;
   string reason;
 };
