/**
 * Another bad operation definition.
 * This time, I have defined an operation whose raises
 * clause references a non-exception type. 
 * RESULT: passed by the IDL compiler
 */

struct s_MyStruct {
  string reason;
};

interface Paul {
  void foo( ) raises (::s_MyStruct);
};