module org
{
  module jacorb
  {
    module test
    {
      interface ClientCallback
      {
        void hello( in string message );
      };

      interface BiDirServer
      {
        void register_callback( in ClientCallback cc );
            
        void callback_hello( in string message );

        long get_open_client_transports();
      };
    };
  };
};
