#include <orb.idl>

module org
{
  module jacorb
  {
    module test
    {
      module bugs
      {
      	module bug351
      	{
        	valuetype WStringValue wstring;

        	valuetype FloatSequence sequence<float>;
        	valuetype FloatSequence2D sequence<FloatSequence>;
        	valuetype WStringValueSequence sequence<WStringValue>;

        	valuetype RetrievalResult
        	{
          		private FloatSequence scores;
          		private WStringValueSequence ids;
          		private long size;

          		FloatSequence getScores();
          		WStringValueSequence getIds();
          		long getSize();

          		void setScores(in FloatSequence scores);
          		void setIds(in WStringValueSequence ids);
          		void setSize(in long size);

          		factory init(in FloatSequence scores,
                	         in WStringValueSequence ids, in long size);
        	};

        	interface ValueServer
        	{
          		RetrievalResult search();
        	};
      	};
      };
    };
  };
};
      