module org
{
    module jacorb
    {
        module test
        {
            module bugs
            {
                module bug700
                {
                    union MyUnion;

                    typedef sequence<MyUnion> MyUnionSeq;

                    union MyUnion switch (boolean)
                    {
                    case TRUE:
                        struct NestedStruct
                        {
                            MyUnionSeq union_seq;
                        } nested_struct;
                    };
                };
            };
        };
    };
};
