/*

 Following IDL does not compile
 and the hHelper.java file is empty!
*/
module org {
  module jacorb {
    module test {
      module bugs {
		module bug84
		{
    			struct h
    			{
        			struct aa
        			{
            			string s;
            			long lng[4];
            			sequence <aa> b;
            			sequence <h> g;
        			} g[3];
    			};
		};
      };
    };
  };    
};
