
module org
{
    module jacorb
    {
        module test
        {
            module bugs
            {
                module bugjac663
                {
                    interface JAC663Server
                    {
                        void send_message (in string config);
                    };
                };
            };
        };
    };
};
