module org
{
    module jacorb
    {
        module test
        {
            module bugs
            {
                module bugjac235
                {
                    interface JAC235
                    {
                        // sleep how many msec.s before replying?
                       string hello(in long sleep);
                    };
                };
            };
        };
    };
};
