

module org
{
    module jacorb
    {
        module test
        {
            module bugs
            {
               module bugjac662
               {
                  interface PingReceiver
                  {
                     string ping();
                     string shutdown();
                  };
               };
            };
        };
    };
};
