

module org
{
    module jacorb
    {
        module test
        {
            module bugs
            {
               module bugjac488
               {
                  interface PingReceiver
                  {
                     oneway void ping();
                     oneway void shutdown();
                  };
               };
            };
        };
    };
};
