#pragma prefix "jacorb.org"

module test {
    module orb {
        module connection {
            interface TestIf {
                
                void op();
                
                oneway void onewayOp();
            };
        };
    };
};
