#pragma prefix "jacorb.org"

module org
{
   module jacorb
   {
      module test
      {
         interface TestIf
         {
            void op();
            oneway void onewayOp();
         };
      };
   };
};
