#include "Tests.idl"

module org
{
   module jacorb
   {
      module test
      {
         interface ExceptionServer
         {
	     void throwRuntimeException(in string message);
             void throwUserException(in long f1, in string f2) 
                raises (NonEmptyException);
         };
      };
   };
};
