#pragma prefix "jacorb.org"

module org
{
   module jacorb
   {
      module test
      {
         interface LongLongSeqServer {

            typedef sequence<long long> SeqLongLong;

            SeqLongLong test1( in SeqLongLong argin, out SeqLongLong argout,
                               inout SeqLongLong arginout );

            SeqLongLong test2( in SeqLongLong argin, out SeqLongLong argout );

            void test3( inout SeqLongLong arginout );
         };
      };
   };
};
