

module org
{
   module jacorb
   {
      module test
      {
         module idl
         {
            module Longs
            {
               const unsigned long long UnsignedValue1 = 18446744073709551616;
            };
         };
      };
   };
};
