// Pragma Testing

#pragma prefix "jacorb.org.Tests"

interface GlobalInterface {};             // Works!
interface GlobalInterfaceNoVersion {};    // Works!

module C
{
   module B
   {
#if 0
#include "Char.idl"
#endif

#ifdef ABNORMAL
#include "abnormal.idl"
#else
#include "Long.idl"
#endif

// Error checking
// #if
// #include "Dummy.idl"
// #endif

      interface AAA {};                   // Works!
      interface BB {};                    // Works!

#pragma ID BB "IDL:COW/B/BB:1.1"            // XXXXXXXXXXXXX
#pragma version BB 1.1                    // Works!
// Error checking
// #pragma version BB 1.22222                // Works!
#pragma prefix Foo                        // Works!
#pragma version AA 1.2                    // Works!

      interface A {};

#pragma version A 1.2     // Works!
// Error checking
// #pragma version A 1.2.1   // Works!
#pragma prefix ""         // PARTIALLY WORKS (should it reset to Global/C/B ???)

      interface AA {};
#pragma ID AA "IDL:myAA:1.2"    // XXXXXXXXXXXX
   };

   interface C_Interface {};          // Works!
#pragma version C_Interface 55        // Works!
// Error checking
// #pragma ID C_Interface "IDL:B/C_Interface:10000"  // XXXXXXXXXXXX
};

#pragma version GlobalInterface 55    // Works!
#pragma ID GlobalInterface "IDL:jacorb.org.Tests.myGlobalInterface:55"    // Works!
