struct qz
{
    string fp;
    string fq;
};

typedef sequence<qz> ra;

interface rc
{
  exception ex {};

    exception rd
    { 
	long re;
	string rf;
    };

    Object rg1() raises(rd);

    oneway void  op1() ;

};
