/**
 * Another test of the name resolution algorithm.
 * Interface Paul employs ThingList but this ought to
 * pick up the global one. Interface Peter, on the other
 * hand, should pick up the local one.
 * RESULT: Runtime error in Jacorb compiler (Undefined name Thing
 *         in reference to sequence definition). IDL passed by OpenORB
 *         compiler
 */

module Mod1
{
   typedef struct s_Thing {
      string name;
   } Thing;

   typedef sequence <Thing> ThingList;
};


module Mod0 {

  struct Thing {
    long lVal;
    short sVal;
  };

  interface Paul {
    Thing pop( in Mod1::ThingList tl );
  };

  typedef sequence <Thing> ThingList;

  interface Peter {
    Thing pop( in ThingList tl );
  };

};
