/**
 * The purpose of this test is to see whether the compiler correctly
 * resolves the names Xtype as used in the raises clause of operation
 * biffa. 
 * RESULT: Correct resolution of name XType by compiler. 
 */
exception XType {
  long severity;
};

interface Paul {
  exception XType {
    string reason;
  };
  
  void biffa() raises ( ::XType, XType );
};