#include "Tests.idl"

module org
{
   module jacorb
   {
      module test
      {
         interface SyncScopeServer
         {
            oneway void oneway_op (in long delay);
            void operation (in long delay);
            long get_oneway_count();
         };
      };
   };
};
