#pragma prefix "org.jacorb"

#include "Tests.idl"

module org
{
   module jacorb
   {
      module test
      {
         interface TimingServer
         {
            long operation (in long id, in long delay);
            char ex_op     (in char ch, in long delay) raises (EmptyException);

            long long server_time (in long delay);
         };
      };
   };
};
