module org
{
   module jacorb
   {
      module test
      {
         module idl
         {
            interface Discriminator
            {

               enum Color{red, green, blue};

               union CharUnionDef switch(char) {
                  case '\x0':
                  char mem1;
                  case 'a':
                  case 'b':
                  case 'd':
                  default:
                  string default_mem;
               };

               union ShortUnionDef switch(short) {
                  case 0:
                  short neg_mem;
                  case 2:
                  short pos_mem;
                  case 3:
                  case 4:
                  case 5:
                  default:
                  string default_mem;
               };

               union EnumUnionDef switch(Color) {
                  case red:
                  Color Color_mem;
                  case green:
                  default:
                  string default_mem;
               };
            };
         };
      };
   };
};
