module Messaging
{
   valuetype ForDeclOpOnly;
   valuetype ForDeclOpOnly
   {
      private boolean byte_order;
      void validateMessageContent();
   };

   valuetype ForDeclMemOnly;
   valuetype ForDeclMemOnly
   {
      private boolean byte_order;
   };


   valuetype ForDeclFacOnly;
   valuetype ForDeclFacOnly
   {
      factory init(in unsigned long w);
   };


   valuetype ForDeclBoth;
   valuetype ForDeclBoth
   {
      private boolean byte_order;
      void validateMessageContent();
   };

   valuetype Test {};

   abstract valuetype Message
   {
      void validateMessageContent();
   };

   valuetype ArbQueueEntry
   {
      private Message m_message;

      Message getMessage();
   };



   // Should Fail
//    valuetype ForDeclFail;

};
