/**
 * Another bad operation definition.
 * This time, I have defined an operation whose raises
 * clause references an enumerated type. 
 * RESULT: FAILURE. 
 * REMARK: The IDL is accepted by the JacORB compiler. 
 *         OpenORB compiler does flag an error for this. 
 */

interface Paul {
  enum Colour { black, white };
  void foo() raises ( Colour );
};