/**
 * The scoped name "One.Two.Three" and should be flagged by
 * either the tokenizer or parser.. 
 * RESULT: FAILURE
 * REMARK: NumberFormatException raised in the compiler. 
 */
 
interface Paul {
  void foo() raises ( One.Two.Three ) ;
};