
/**
 * The following IDL contains two interfaces that
 * are only forward declared. 
 * As the use of these interfaces is merely as operation
 * parameters and return types, the IDL is correct. 
 * The IDL has identified a bug in the following:
 * <ul>
 * <li><b>JacORB</b>: the lack of a definition of the forward declared interfaces
 * seems to give rise to an infinite loop.</li>
 * </ul>
 * @idlCompileOK TRUE
 */
module Mod1 {
  interface Peter;
  interface Paul;
};

module Mod2 {
  interface Mary {
    ::Mod1::Paul foo( in ::Mod1::Peter arg );
  };
};