
/**
 * This IDL is legal. The compiler should correctly
 * resolve the names and generate code accordingly. 
 * RESULT: SUCCESS
 * REMARK: Generated code looks OK. MyStructList is resolved to
 *         an array type. 
 */
 
module Mod0 {
  typedef enum eColour { red, orange, york, blue } Colour;
  
  typedef struct sMyStruct {
    string name;
    string address;
  } MyStruct;
  
  module Mod1 {
  
    exception OutOfBounds {
      short index;
    };
    
    typedef sequence <MyStruct> MyStructList;
  
    interface Paul {
      attribute Colour col;
      MyStruct getElementAt(in short index, in MyStructList msl) raises ( OutOfBounds );
    };
  };
};