/**
 * Define a struct type within a module and alias it. 
 * Then define a sequence type for it. 
 * RESULT: SUCCESS
 * REMARK: compare result with scoping6.idl 
 */
 
module Mod0 {
  typedef struct s_MyStruct {
    string name;
    string address;
  } MyStruct;
  
  typedef sequence <MyStruct> MyStructList;
};