
/**
 * Define a struct type at file scope and alias it. 
 * Then define a sequence type for it. 
 * RESULT: SUCCESS
 * REMARK: This contrasts starkly with scoping6.idl which
 *         gave a runtime exception. 
 */ 

typedef struct s_MyStruct {
  string name;
  string address;
} MyStruct;

interface Paul {
  typedef sequence <MyStruct> MyStructList;
  MyStruct getElementAt( in long index, in MyStructList msl );
};
