module org
{
	module jacorb
   	{
    	module test
      	{
         	module bugs
         	{
         		module bugpt480
				{
					exception ExceptionOne
					{
						string reason;
					};
				
					interface Foo
					{
						exception ExceptionTwo
						{
							unsigned long reason;
						};
					};
				};
			};
		};
	};
};