
module Mod0 {
  typedef enum eColour { red, orange, york, blue } Colour;

  typedef struct sMyStruct {
    string name;
    string address;
    long lname;
  } MyStruct;

  interface Paul {
    attribute Colour col;
  };
};
