struct qz
{
    string fp;
    string fq;
};

typedef sequence<qz> ra;

interface rc
{
  exception ex {};

    exception rd
    { 
	long re;
	string rf;
    };

    Object rg1() raises(rd);

    oneway void  op1() ;

    attribute long attr1 getraises (ex) setraises (rd);
    attribute long attr2 setraises (ex) getraises (rd);
    attribute long attr3 setraises (ex, rd);
    attribute long attr4 getraises (ex, rd);

    readonly attribute long attr5 raises (ex, rd);
};
