module org
{
   module jacorb
   {
      module test
      {
         module idl
         {

             typedef struct Lime6 {
                 char WaterMelon6[13];
             } Coconut6[15];
    
             typedef struct Sultana7{
                 sequence<sequence<sequence<Lime6,9> ,7> ,4>  GaliaMelon7;
             } Turnip7;

             interface LimeTest
                 {
                     void op( in Lime6 l );
                 };

         };
      };
   };
};
