#!/usr/bin/sh
# shell script to run two servers and one client performing an overall test
# $Id$

# TODO: adapt to suit your settings
ORB="${JACORB}"
NSURL="${HOME}/public_html/jacorb/NS_Ref"
DSURL="${HOME}/public_html/jacorb/DS_Ref"

# start name server
ns ${NSURL} &
#echo '<enter> for continue after startup of name server'; 
#read i;

cd ${ORB}/classes;

jaco org.jacorb.orb.domain.DomainServer ${DSURL} &
echo '<enter> for continue after startup of domain server'; 
read i;

# start domain server with some context test policies
jaco org.jacorb.orb.domain.test.DomainTesterServer &
echo '<enter> for continue after startup of test server'; 
read i;

# start client domain tester with input redirection
jaco org.jacorb.orb.domain.test.DomainTesterClient < ${ORB}/src/org/jacorb/orb/domain/test/inputfiles/DomainTesterClient.scenario

#echo 'wait until <return>'; read i;


#echo 'type <enter> to run reference tester'; read i;
# start reference tester with input redirection
jaco org.jacorb.orb.domain.test.ReferenceTester < ${ORB}/src/org/jacorb/orb/domain/test/inputfiles/ReferenceTester.1

# clean up
if [ $# = '0' ] 	# $# ist Anzahl der Argumente
then 
    echo "cleaning up ..."
    killer jaco
    killer java
fi
# don't clean up, if any arguments are given
