#ifndef _MGM_IDL_
#define _MGM_IDL_


//#ifndef _PRE_3_0_COMPILER_
#pragma prefix "omg.org"
#include "PortableGroup.idl"
/*
#else
import ::PortableGroup;
#endif //_PRE_3_0_COMPILER_
*/

module MGM
{
/*
#ifndef _PRE_3_0_COMPILER_
   typeprefix MIOP "omg.org";
#endif // _PRE_3_0_COMPILER_
*/
   // Property values
   typedef long GroupCreationMode;

   const GroupCreationMode CREATE_ADDRESS_DEFERED = 0;
   const GroupCreationMode CREATE_ADDRESS_GENERATED = 1;
   const GroupCreationMode CREATE_ADDRESS_SUPPLIED = 2;

   interface ObjectGroupFactory :
      PortableGroup::GenericFactory,
      PortableGroup::PropertyManager,
      PortableGroup::ObjectGroupManager
   {
   };

};
#endif // _MGM_idl
