module demo
{
    module hello {

        interface GoodDay {
            
            string hello_simple();
            
            wstring hello_wide( in wstring msg );            
        };
               
    };

};
