/*
 *        JacORB - a free Java ORB
 *
 *   Copyright (C) 1999-2014 Gerald Brose / The JacORB Team.
 *
 *   This library is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU Library General Public
 *   License as published by the Free Software Foundation; either
 *   version 2 of the License, or (at your option) any later version.
 *
 *   This library is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *   Library General Public License for more details.
 *
 *   You should have received a copy of the GNU Library General Public
 *   License along with this library; if not, write to the Free
 *   Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */
package org.jacorb.ir.gui.typesystem;

/**
 * This interface was generated by a SmartGuide.
 *
 */
public interface AbstractContainer {

    /**
     * Creates TypeSystemNodes for all contained objects.
     * Default implementation that works for "real" CORBA containers.
     * For other classes (e.g. IRStruct), which are not real CORBA containers,
     * this Method is overridden with individual code for retrieving the members.
     * @return org.omg.CORBA.Object 
     */
    org.jacorb.ir.gui.typesystem.ModelParticipant[] contents();
}

