/*
 *        JacORB - a free Java ORB
 *
 *   Copyright (C) 1999-2014 Gerald Brose / The JacORB Team.
 *
 *   This library is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU Library General Public
 *   License as published by the Free Software Foundation; either
 *   version 2 of the License, or (at your option) any later version.
 *
 *   This library is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *   Library General Public License for more details.
 *
 *   You should have received a copy of the GNU Library General Public
 *   License along with this library; if not, write to the Free
 *   Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */
package org.jacorb.ir.gui.typesystem;


/**
 * This interface was generated by a SmartGuide.
 *
 */

public interface Interface
{
    /**
     * Returns all fields, including fields of any super interfaces
     * @return org.jacorb.ir.gui.typesystem.TypeSystemNode[]
     */
    public TypeSystemNode[] getAllFields();
    /**
     * Returns all operations, including operations of any super interfaces
     * @return org.jacorb.ir.gui.typesystem.TypeSystemNode[]
     */
    public TypeSystemNode[] getAllOperations();
    /**
     * Returns all super interfaces
     * @return org.jacorb.ir.gui.typesystem.Interface[]
     */
    public Interface[] getSuperInterfaces();
}

