
module org
{
    module jacorb
    {
        module demo
        {
            module sas
            {
                interface SASDemo
                {
                    void printSAS();

                    void shutdown ();
                };
            };
        };
    };
};
