
module org
{
    module jacorb
    {
        module demo
        {
            module maven
            {
                interface GoodDay
                {
                    string hello_simple();

                    wstring hello_wide( in wstring msg );

                    void shutdown ();
                };
            };
        };
    };
};
