module test
{
module dynany
{
   // example empty exception
   exception EmptyException {};

   // example non-empty exception
   exception NonEmptyException
   {
      long field1;
      string field2;
   };

   // example Struct type
   struct StructType
   {
      long field1;
      string field2;
   };      
};};
