// grid.idl
// IDL defintion of a 2-D grid:

module demo
{
module grid 
{ 
    interface MyServer
    {
	typedef fixed <5,2> fixedT;

	readonly attribute short height;  // height of the grid
	readonly attribute short width;   // width of the grid

	// set the element [n,m] of the grid, to value:
	void set(in short n, in short m, in fixedT value);

	// return element [n,m] of the grid:
	fixedT get(in short n, in short m);

	exception MyException
	{
	    string why;
	};

	short opWithException() raises( MyException );

    };
};
};
