module demo {
    module poa_monitor {
	module foox {

		interface Foo {
			void compute(in long l);
			void deactivate();
		};

		interface FooFactory {
			Foo createFoo(in string id);
			string getServerDescription();
		};
	};
    };
};
