// -*- IDL -*-

// $Id: AsyncStartupWaiter.idl 14 2007-02-01 15:49:12Z mitza $

module ImplementationRepository
{
  struct StartupInfo {
    string name;
    string partial_ior;
    string ior;
  };

  interface AsyncStartupWaiter
  {
    StartupInfo wait_for_startup(in string name);
  };
};

