// -*- IDL -*-

// $Id: ImR_Activator.idl 14 2007-02-01 15:49:12Z mitza $

#include "ImplRepo.idl"

module ImplementationRepository
{
  interface Activator
  {
    // Tells the activator to launch a server with the given information.
    void start_server(in string name, in string cmdline,
      in string dir, in EnvironmentList env) raises(CannotActivate);

    oneway void shutdown();
  };
};

