
//----------------------------------------------------
// The following code was generated by CUP v0.9e
// Sat Apr 14 14:00:14 GMT+02:00 2001
//----------------------------------------------------

package org.jacorb.idl;

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SHORT = 35;
  static final int CONTEXT = 9;
  static final int FACTORY = 15;
  static final int CONST = 8;
  static final int TRUNCATABLE = 41;
  static final int WCHAR = 48;
  static final int SEMI = 50;
  static final int ENUM = 13;
  static final int READONLY = 33;
  static final int RAISES = 32;
  static final int COMMA = 51;
  static final int RPAREN = 59;
  static final int SEQUENCE = 34;
  static final int DOUBLE = 12;
  static final int STRUCT = 37;
  static final int VALUEBASE = 45;
  static final int LPAREN = 58;
  static final int OUT = 28;
  static final int FALSE = 16;
  static final int TILDE = 74;
  static final int RCBRACE = 61;
  static final int OBJECT = 25;
  static final int DBLQUOTE = 67;
  static final int LCBRACE = 60;
  static final int FLOAT = 18;
  static final int WSTRING = 49;
  static final int GREATERTHAN = 65;
  static final int FIXED = 17;
  static final int SUPPORTS = 38;
  static final int NUMBER = 81;
  static final int LESSTHAN = 64;
  static final int ABSTRACT = 2;
  static final int SLASH = 72;
  static final int VALUETYPE = 46;
  static final int TRUE = 40;
  static final int NATIVE = 24;
  static final int LONG = 22;
  static final int PLUS = 56;
  static final int PERCENT = 73;
  static final int QUOTE = 66;
  static final int PSEUDO = 31;
  static final int UNION = 44;
  static final int MODULE = 23;
  static final int INTERFACE = 21;
  static final int CHAR = 7;
  static final int BOOLEAN = 5;
  static final int SWITCH = 39;
  static final int STAR = 52;
  static final int VOID = 47;
  static final int INOUT = 20;
  static final int PUBLIC = 30;
  static final int OCTET = 26;
  static final int AMPERSAND = 71;
  static final int DOT = 53;
  static final int INT = 80;
  static final int CIRCUM = 70;
  static final int EOF = 0;
  static final int ONEWAY = 27;
  static final int DBLCOLON = 75;
  static final int DEFAULT = 11;
  static final int FLOAT_NUMBER = 83;
  static final int FIXED_NUMBER = 84;
  static final int RSBRACE = 63;
  static final int MINUS = 57;
  static final int IN = 19;
  static final int CH = 79;
  static final int error = 1;
  static final int ATTRIBUTE = 4;
  static final int UNSIGNED = 43;
  static final int ID = 78;
  static final int CUSTOM = 10;
  static final int COLON = 54;
  static final int BSLASH = 68;
  static final int LSBRACE = 62;
  static final int ANY = 3;
  static final int CASE = 6;
  static final int EXCEPTION = 14;
  static final int RSHIFT = 76;
  static final int STRING = 36;
  static final int BAR = 69;
  static final int PRIVATE = 29;
  static final int LSHIFT = 77;
  static final int TYPEDEF = 42;
  static final int EQUALS = 55;
  static final int LONG_NUMBER = 82;
};

