
//----------------------------------------------------
// The following code was generated by CUP v0.9e
// Mon Jun 09 15:59:37 BST 2003
//----------------------------------------------------

package org.jacorb.idl;

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SHORT = 36;
  static final int CONTEXT = 9;
  static final int FACTORY = 15;
  static final int CONST = 8;
  static final int TRUNCATABLE = 42;
  static final int WCHAR = 49;
  static final int SEMI = 51;
  static final int ENUM = 13;
  static final int SPACE = 80;
  static final int READONLY = 34;
  static final int RAISES = 33;
  static final int COMMA = 52;
  static final int RPAREN = 60;
  static final int SEQUENCE = 35;
  static final int DOUBLE = 12;
  static final int STRUCT = 38;
  static final int VALUEBASE = 46;
  static final int LPAREN = 59;
  static final int OUT = 29;
  static final int FALSE = 16;
  static final int TILDE = 75;
  static final int RCBRACE = 62;
  static final int OBJECT = 26;
  static final int DBLQUOTE = 68;
  static final int LCBRACE = 61;
  static final int FLOAT = 18;
  static final int WSTRING = 50;
  static final int GREATERTHAN = 66;
  static final int FIXED = 17;
  static final int SUPPORTS = 39;
  static final int NUMBER = 83;
  static final int LESSTHAN = 65;
  static final int ABSTRACT = 2;
  static final int SLASH = 73;
  static final int VALUETYPE = 47;
  static final int TRUE = 41;
  static final int NATIVE = 25;
  static final int LONG = 23;
  static final int PLUS = 57;
  static final int PERCENT = 74;
  static final int QUOTE = 67;
  static final int PSEUDO = 32;
  static final int UNION = 45;
  static final int MODULE = 24;
  static final int INTERFACE = 21;
  static final int CHAR = 7;
  static final int BOOLEAN = 5;
  static final int SWITCH = 40;
  static final int STAR = 53;
  static final int VOID = 48;
  static final int INOUT = 20;
  static final int PUBLIC = 31;
  static final int OCTET = 27;
  static final int AMPERSAND = 72;
  static final int DOT = 54;
  static final int CIRCUM = 71;
  static final int EOF = 0;
  static final int ONEWAY = 28;
  static final int DBLCOLON = 76;
  static final int DEFAULT = 11;
  static final int FLOAT_NUMBER = 85;
  static final int LOCAL = 22;
  static final int FIXED_NUMBER = 86;
  static final int RSBRACE = 64;
  static final int MINUS = 58;
  static final int IN = 19;
  static final int CH = 82;
  static final int error = 1;
  static final int ATTRIBUTE = 4;
  static final int UNSIGNED = 44;
  static final int ID = 81;
  static final int CUSTOM = 10;
  static final int COLON = 55;
  static final int BSLASH = 69;
  static final int LSBRACE = 63;
  static final int ANY = 3;
  static final int CASE = 6;
  static final int EXCEPTION = 14;
  static final int RSHIFT = 77;
  static final int STRING = 37;
  static final int LDBLQUOTE = 79;
  static final int BAR = 70;
  static final int PRIVATE = 30;
  static final int LSHIFT = 78;
  static final int TYPEDEF = 43;
  static final int EQUALS = 56;
  static final int LONG_NUMBER = 84;
};

