module demo
{
    module bidir 
    { 
        interface ClientCallback
        {
            void hello( in string message );
        };

        interface Server
        {
            void register_callback( in ClientCallback cc );
            
            void callback_hello( in string message );
        };
    };
};
