module demo {

   module value {

         valuetype boxedLong   long;
         valuetype boxedString string;

         valuetype Node {
            public long id;
            public Node next;
         };

         interface ValueServer {
            string receive_long   (in boxedLong p1, in boxedLong p2);
            string receive_string (in boxedString s1, in boxedString s2);

            string receive_list   (in Node node_);
         };

   };

};
