/***** Copyright (c) 1999-2000 Object Management Group. Unlimited rights to 
       duplicate and use this code are hereby granted provided that this 
       copyright notice is included.
*****/

/***** This class is generated by an IDL compiler and is ORB-vendor specific. 
       A "dummy" implementation is provided so that the "official" org.omg.*
       packages may be compiled.  In order to actually use a Java ORB,
       the ORB vendor's implementation will provide a "real"
       implementation of the class.

       In order to be conformant the class shall support the signatures
       specified here, but will have an orb-specific implementation.

       The class may support additional vendor specific functionality.
       It shall have at least the inheritance relationships specified
       here. Any additional (vendor specific) inheritance relationships may 
       only be with other classes and interfaces that are guaranteed to be 
       present in the JDK core.
*****/

package org.omg.PortableServer;

public class IdUniquenessPolicyValue implements org.omg.CORBA.portable.IDLEntity {

    public static final int _UNIQUE_ID = 0;
    public static final IdUniquenessPolicyValue UNIQUE_ID = 
        new IdUniquenessPolicyValue(_UNIQUE_ID);

    public static final int _MULTIPLE_ID = 1;
    public static final IdUniquenessPolicyValue MULTIPLE_ID = 
        new IdUniquenessPolicyValue(_MULTIPLE_ID);

    public int value() {
        throw new org.omg.CORBA.NO_IMPLEMENT();
    }

    public static IdUniquenessPolicyValue from_int(int val) 
                       /* Issue 3669 throws org.omg.CORBA.BAD_PARAM */ {
    switch (val) {
    case _UNIQUE_ID:
        return UNIQUE_ID;
    case _MULTIPLE_ID:
        return MULTIPLE_ID;
    default:
        throw new org.omg.CORBA.BAD_PARAM();
    }
    }

    protected IdUniquenessPolicyValue(int _value) {
        throw new org.omg.CORBA.NO_IMPLEMENT();
    }

}
