
module org
{
    module jacorb
    {
        module demo
        {
            module ssl
            {
                interface SSLDemo
                {
                    void printCert();
                    void shutdown ();
                };
            };
        };
    };
};
