
package org.jacorb.ir.gui.typesystem.remote;


import org.omg.CORBA.*;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class IRArray extends IRNodeWithType {



/**
 * IRSequence constructor comment.
 */
protected IRArray() {
	super();
}
/**
 * IRSequence constructor comment.
 * @param irObject org.omg.CORBA.IRObject
 */
protected IRArray(org.omg.CORBA.IRObject irObject) {
	super(irObject);
	ArrayDef arrayDef = ArrayDefHelper.narrow((org.omg.CORBA.Object)irObject);
	setAssociatedTypeSystemNode(RemoteTypeSystem.createTypeSystemNode(arrayDef.element_type_def()));
	setName(getAssociatedType()+"["+arrayDef.length()+"]");
}
}





