
package org.jacorb.ir.gui.typesystem.remote;


import org.jacorb.ir.gui.typesystem.*;
import javax.swing.tree.*;
/**
 * This class was generated by a SmartGuide.
 * 
 */
public class IREnumMember extends IRNode {



/**
 * IREnumMember constructor comment.
 */
protected IREnumMember() {
	super();
}
/**
 * This method was created by a SmartGuide.
 * @param name java.lang.String
 */
protected IREnumMember ( String name) {
	setName(name);
}
/**
 * This method was created by a SmartGuide.
 * @return java.lang.String
 */
public static String nodeTypeName() {
	return "";
}
}











