package org.jacorb.ir.gui.typesystem.remote;

import javax.swing.tree.*;

/**
 * This class was generated by a SmartGuide.
 * 
 */

public class IRStructMember extends IRNodeWithType 
{

    /**
     * IRStructMember constructor comment.
     */
    protected IRStructMember() {
	super();
    }
 
    /**
     * @param structMember org.omg.CORBA.StructMember
     */

    protected IRStructMember( org.omg.CORBA.StructMember structMember) 
    {
	setName(structMember.name);
	setAssociatedTypeSystemNode(
             RemoteTypeSystem.createTypeSystemNode( structMember.type_def) );
    }

    /**
     * @return java.lang.String
     */

    public static String nodeTypeName() 
    {
	return ""; // soll ja so ähnlich aussehen wie IDL, und da steht nur der Name
    }

}





