
package org.jacorb.ir.gui.typesystem.remote;


/**
 * This class was generated by a SmartGuide.
 * 
 */
 
 import java.util.*;
 import org.omg.CORBA.*;
 import javax.swing.tree.*;
 
public class IRTypedef extends IRNode {
	static {
	}



/**
 * Default-Konstruktor: wird von TypeSystem.createNode(...) benutzt
 */
public IRTypedef ( ) {
	super();
}
/**
 * This method was created by a SmartGuide.
 * @return java.lang.String
 */
public static String nodeTypeName() {
	return "typedef";
}
}











