
package org.jacorb.ir.gui.typesystem.remote;


import javax.swing.tree.*;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class IRUnionMember extends IRNodeWithType {



/**
 * IRUnionMember constructor comment.
 */
protected IRUnionMember() {
	super();
}
/**
 * This method was created by a SmartGuide.
 * @param structMember org.omg.CORBA.StructMember
 */
protected IRUnionMember ( org.omg.CORBA.UnionMember unionMember) {
	setName(unionMember.name);
	setAssociatedTypeSystemNode(RemoteTypeSystem.createTypeSystemNode(unionMember.type_def));	
}
/**
 * This method was created by a SmartGuide.
 * @return java.lang.String
 */
public static String nodeTypeName() {
	return "";	// soll ja so ähnlich aussehen wie IDL, und da steht nur der Name
}
}











