module demo
{
    module trace
        {
            interface FooServer
                {
                    void anOperation(in string param);
                };

            interface FooRelayServer
                {
                    void anotherOperation(in string param);
                };

        };
};
