// Test suite part 1: base types, constant definitions

module basetypes
{
    // definitions

    const long arrayBound = 011;
    
    const long LEN = 5;
    typedef string <basetypes::LEN> ls;


    // test uses

    struct ArrayContainer 
    {
	ls l;
    };

    interface N {
	void notify();
    };



};
