module org {
  module jacorb {
    module test {
      module bugs {
        module bug401 {
  
          valuetype A {
	    		public long aa;
          };

          valuetype B : A {
	    		public long bb;
          };

          interface AnyServer {
	    		A getA();
	    		B getB();

	    		// get an A passed as an any
	    		any getAnyA();

	    		// get a B passsed as an any
	    		any getAnyB();

            // return a sequence of A and B as Anys
	    		typedef sequence<any> AnySeq;

	    		AnySeq getAnyAB();
          };
        };
      };
    };
  };    
};