module org
{
    module jacorb
    {
        module test
        {
            module dii
            {
                interface DIIServer
                {
                    attribute long long_number;

                    exception DIIException {
                        string why;
                    };

                    string writeNumber( in long i ) raises (DIIException);

                    void add(in long i, in long j, out long r );

                    void raiseException() raises (DIIException);

                    oneway void notify( in string msg );
                };
            };
        };
    };
};

