
module org
{
   module jacorb
   {
      module test
      {
          module bugs
          {
              module bug960
              {
                  interface Hello
                  {
                      void sayHello();
                  };
              };
          };
      };
   };
};
