
/**
 * Another bad operation definition. 
 * In my view, thie IDL should be illegal as exception
 * types are being used as parameters and arguments to
 * operations. This could be up for debate but, as a purist,
 * I think we should regard exceptions as "special" types. 
 * RESULT: passed by the IDL compiler. 
 */

exception Ex_1 {};

interface Paul {
  Ex_1 foo( in Ex_1 arg1 );
};