/**
 * The following incorrect interface definition contains
 * a repeated use of an argument name within an operation
 * declaration. As an operation defines a new scope, this
 * should get caught. Otherwise, there is the danger that
 * uncompilable stub and skeleton code is generated.
 * RESULT: error is trapped by the idl compiler. 
 */
 
interface Paul {
  void foo( in long arg1, inout string arg1 );
};