/***** Copyright (c) 1999 Object Management Group. Unlimited rights to 
       duplicate and use this code are hereby granted provided that this 
       copyright notice is included.
*****/

/***** This class is generated by an IDL compiler and is ORB-vendor specific. 
       A "dummy" implementation is provided so that the "official" org.omg.*
       packages may be compiled.  In order to actually use a Java ORB,
       the ORB vendor's implementation will provide a "real"
       implementation of the class.

       In order to be conformant the class shall support the signatures
       specified here, but will have an orb-specific implementation.

       The class may support additional vendor specific functionality.
       It shall have at least the inheritance relationships specified
       here. Any additional (vendor specific) inheritance relationships may 
       only be with other classes and interfaces that are guaranteed to be 
       present in the JDK core.
*****/

package org.omg.CORBA.ContainedPackage;

public final class Description implements org.omg.CORBA.portable.IDLEntity {

    public org.omg.CORBA.DefinitionKind kind;
    public org.omg.CORBA.Any value;

    public Description() {
        throw new org.omg.CORBA.NO_IMPLEMENT();
    }

    public Description(org.omg.CORBA.DefinitionKind kind, 
                    org.omg.CORBA.Any value) {
        
        throw new org.omg.CORBA.NO_IMPLEMENT();
    }
}
