/***** Copyright (c) 1999 Object Management Group. Unlimited rights to 
       duplicate and use this code are hereby granted provided that this 
       copyright notice is included.
*****/

/***** This class is generated by an IDL compiler and is ORB-vendor specific. 
       A "dummy" implementation is provided so that the "official" org.omg.*
       packages may be compiled.  In order to actually use a Java ORB,
       the ORB vendor's implementation will provide a "real"
       implementation of the class.

       In order to be conformant the class shall support the signatures
       specified here, but will have an orb-specific implementation.

       The class may support additional vendor specific functionality.
       It shall have at least the inheritance relationships specified
       here. Any additional (vendor specific) inheritance relationships may 
       only be with other classes and interfaces that are guaranteed to be 
       present in the JDK core.
*****/

package org.omg.PortableServer.POAPackage;

public final class ServantNotActiveHelper {

    public static void insert(org.omg.CORBA.Any any, 
                 org.omg.PortableServer.POAPackage.ServantNotActive _value) {
        throw new org.omg.CORBA.NO_IMPLEMENT();
    }

    public static org.omg.PortableServer.POAPackage.ServantNotActive extract(
            org.omg.CORBA.Any any) {
        throw new org.omg.CORBA.NO_IMPLEMENT();
    }

    public static org.omg.CORBA.TypeCode type() {
        throw new org.omg.CORBA.NO_IMPLEMENT();
    }

    public static java.lang.String id() {
        throw new org.omg.CORBA.NO_IMPLEMENT();
    }
    public static org.omg.PortableServer.POAPackage.ServantNotActive read(
            org.omg.CORBA.portable.InputStream _input) {
        throw new org.omg.CORBA.NO_IMPLEMENT();
    }

    public static void write (org.omg.CORBA.portable.OutputStream _output, 
                org.omg.PortableServer.POAPackage.ServantNotActive _value) {
        throw new org.omg.CORBA.NO_IMPLEMENT();
    }

}
