module test
{
  module memoryusage
    {
      interface Session
	{
          string getID();
	};

      interface SessionFactory
	{
          Session get_Session(in string userName,
                              in string fullName,
                              in string emailAddress,
                              in string ip);

          void releaseSession(in Session s);
	};
    };
};
