
package org.jacorb.ir.gui.typesystem;


/**
 * This interface was generated by a SmartGuide.
 * 
 */
public interface AbstractContainer {



/**
 * Erzeugt TypeSystemNodes für alle contained Objekte.
 * Default-Implementierung, die für "echte" CORBA-Container funktionert.
 * Für andere Klassen (z.B. IRStruct), die keine echten CORBA-Container sind,
 * wird diese Methode überschrieben mit individuellem Code zum Auslesen der members.
 * @return org.omg.CORBA.Object
 */
jacorb.ir.gui.typesystem.ModelParticipant[] contents ( ) ;
}

