/*
 *        JacORB - a free Java ORB
 *
 *   Copyright (C) 1999-2002 Gerald Brose
 *
 *   This library is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU Library General Public
 *   License as published by the Free Software Foundation; either
 *   version 2 of the License, or (at your option) any later version.
 *
 *   This library is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *   Library General Public License for more details.
 *
 *   You should have received a copy of the GNU Library General Public
 *   License along with this library; if not, write to the Free
 *   Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */
package org.jacorb.ir.gui.typesystem;

/**
 * This interface was generated by a SmartGuide.
 * 
 */
public interface AbstractContainer {

    /**
     * Erzeugt TypeSystemNodes für alle contained Objekte.
     * Default-Implementierung, die für "echte" CORBA-Container funktionert.
     * Für andere Klassen (z.B. IRStruct), die keine echten CORBA-Container sind,
     * wird diese Methode überschrieben mit individuellem Code zum Auslesen der members.
     * @return org.omg.CORBA.Object
     */
    org.jacorb.ir.gui.typesystem.ModelParticipant[] contents();
}








