
package org.jacorb.ir.gui.typesystem;


/**
 * This class was generated by a SmartGuide.
 * 
 */
class IllegalChildException extends Exception {



/**
 * IllegalChildException constructor comment.
 */
public IllegalChildException() {
	super();
}
/**
 * IllegalChildException constructor comment.
 * @param s java.lang.String
 */
public IllegalChildException(String s) {
	super(s);
}
}

