package org.jacorb.ir.gui.typesystem;


/**
 * This interface was generated by a SmartGuide.
 * 
 */

public interface Interface 
{
    /**
     * Gibt alle Fields inkl. der Fields der Super-Interfaces zurück
     * @return org.jacorb.ir.gui.typesystem.TypeSystemNode[]
     */
    public TypeSystemNode[] getAllFields();
    /**
     * Gibt alle Fields inkl. der Fields der Super-Interfaces zurück
     * @return org.jacorb.ir.gui.typesystem.TypeSystemNode[]
     */
    public TypeSystemNode[] getAllOperations();
    /**
     * This method was created by a SmartGuide.
     * @return org.jacorb.ir.gui.typesystem.Interface[]
     */
    public Interface[] getSuperInterfaces();
}








