
package org.jacorb.ir.gui.typesystem;


/**
 * This interface was generated by a SmartGuide.
 * 
 */
public interface TypeAssociator {



/**
 * This method was created by a SmartGuide.
 * @return java.lang.String
 */
public String getAssociatedType();
/**
 * This method was created by a SmartGuide.
 * @return org.jacorb.ir.gui.typesystem.TypeSystemNode
 */
public TypeSystemNode getAssociatedTypeSystemNode();
}







